### ISSUE TITLE
Add ability to define social share image

### ISSUE THREAD

**Issue by peterkeating** [moov2/Moov2.Orchard.SEO#8]
When creating a new content item it would be useful within the meta info part to be able to define what image will be used when the page is shared on social media sites (e.g. Twitter, Facebook).

**Comment by JoeBerkley** [comment]
Added in https://github.com/moov2/Moov2.Orchard.SEO/commit/7938461765125e580df5e054c753e2214e99f69c and enhanced in https://github.com/moov2/Moov2.Orchard.SEO/commit/f049702f8e1c2bdab2335a000fb184b646ba1bf3
